"""Generate a copy-pasteable Claude prompt for owner clustering, one file per commune.

Usage:
    python scripts/ner/generate_clustering_prompt.py
    python scripts/ner/generate_clustering_prompt.py --commune abymes
"""

import argparse
from pathlib import Path

BASE = Path(
    "C:/Users/marie/Dropbox/Personnelle/2. Travail/1. Recherche/3. JMP/"
    "3. OCR/2. TrOCR/5. Data (output)/ECES"
)
PAIRS_DIR = BASE / "NER_datasets/llm/owner_pairs"
PROMPTS_DIR = BASE / "NER_datasets/llm/owner_pairs/prompts"

PROMPT_TEMPLATE = """\
I am working on 19th-century French colonial civil registries from Guadeloupe (commune: {commune}).
The records were transcribed by OCR from handwritten documents.

Read the file at:
  {pairs_file}

This file was generated by aggregating owner_name_raw and habitation_name_raw fields across all
three cleaned CSV files (births, deaths, marriages) for this commune, located at:
  {cleaned_dir}/ner_birth.csv
  {cleaned_dir}/ner_death.csv
  {cleaned_dir}/ner_marriage.csv

It contains a JSON array of unique (owner_name_raw, habitation_name_raw, count) tuples. Each entry
is one distinct (owner, plantation) combination observed in the records, with its frequency count.
Many entries refer to the same real person but appear under different spellings, OCR errors,
abbreviations, or partial names.

Your task: identify all clusters of entries that refer to the same individual or legal entity.

Rules:
- Use BOTH the owner name AND the plantation name as evidence. Same plantation = strong signal of same owner.
- Consider: OCR errors (P/B/D confusion, T/F, ai/oi, accents missing/wrong), abbreviations
  (Sr/Sieur, Mme/Dame, Vve/Veuve, Dlle/Demoiselle), name order swaps, partial names.
- héritiers X and X are the same family/estate — merge them.
- père/fils = different generations — keep separate unless plantation confirms same person.
- Dame Veuve X ≠ X (widow ≠ deceased husband) — keep separate.
- [illisible], [non précisé] and similar noise entries → canonical: null.
- Entries where owner_name_raw is a plantation description (e.g. "l'habitation Belleplaine") → canonical: null.
- Do NOT merge people who share only a common surname if their first names differ.
- For each cluster pick the canonical name: the most complete and most frequent form.

Output a JSON array only, no commentary. Write it to:
  {clusters_file}

Each element:
{{
  "canonical": "<canonical owner name, or null>",
  "variants": ["<raw name 1>", "<raw name 2>", ...]
}}

Only include entries that need to be merged or mapped to null.
Singletons that are already clean can be omitted — they will keep their raw name as canonical.
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--commune", type=str, default=None)
    args = parser.parse_args()

    PROMPTS_DIR.mkdir(parents=True, exist_ok=True)

    if args.commune:
        pair_files = [PAIRS_DIR / f"{args.commune}_owner_pairs.json"]
    else:
        pair_files = sorted(PAIRS_DIR.glob("*_owner_pairs.json"))

    for pair_file in pair_files:
        commune = pair_file.stem.replace("_owner_pairs", "")
        clusters_file = PAIRS_DIR / f"{commune}_owner_clusters.json"

        prompt = PROMPT_TEMPLATE.format(
            commune=commune,
            pairs_file=pair_file,
            clusters_file=clusters_file,
            cleaned_dir=PAIRS_DIR.parent / "cleaned",
        )

        out_path = PROMPTS_DIR / f"{commune}_clustering_prompt.txt"
        out_path.write_text(prompt, encoding="utf-8")
        print(f"  {commune} → {out_path}")

    print("Done. Open the .txt file and paste its contents into Claude.")


if __name__ == "__main__":
    main()
